import catalogue from "@/_data/products.json";

/**
 * SERVER ONLY. products.json is a ~5.5 MB snapshot generated by
 * scripts/fetch-catalogue.js — importing this module from a client component
 * would ship the whole catalogue to the browser. Client code should call
 * /api/products, and use _lib/format.js for the pure helpers.
 */
export async function getAllProducts() {
  return catalogue.products;
}

export async function getProductByHandle(handle) {
  return catalogue.products.find((p) => p.handle === handle) || null;
}
